"""create job_parts table

Revision ID: 3092be20ec79
Revises: 8e6d2de1b60c
Create Date: 2026-08-02 16:08:56.931894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3092be20ec79'
down_revision = '8e6d2de1b60c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_parts',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(precision=53), nullable=False),
    sa.Column('unit_cost_at_time', sa.Float(precision=53), nullable=False),
    sa.Column('unit_price_at_time', sa.Float(precision=53), nullable=False),
    sa.Column('overdrawn', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('shortfall', sa.Float(precision=53), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_parts_inventory_item_id'), 'job_parts', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_job_parts_job_id'), 'job_parts', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_parts_tenant_id'), 'job_parts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_parts_tenant_id'), table_name='job_parts')
    op.drop_index(op.f('ix_job_parts_job_id'), table_name='job_parts')
    op.drop_index(op.f('ix_job_parts_inventory_item_id'), table_name='job_parts')
    op.drop_table('job_parts')
    # ### end Alembic commands ###
