"""create job_labor_entries table

Revision ID: be92032f8ef8
Revises: c79ffe32696c
Create Date: 2026-08-01 18:45:36.007349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be92032f8ef8'
down_revision = 'c79ffe32696c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_labor_entries',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('technician_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_labor_entries_job_id'), 'job_labor_entries', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_labor_entries_technician_id'), 'job_labor_entries', ['technician_id'], unique=False)
    op.create_index(op.f('ix_job_labor_entries_tenant_id'), 'job_labor_entries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_labor_entries_tenant_id'), table_name='job_labor_entries')
    op.drop_index(op.f('ix_job_labor_entries_technician_id'), table_name='job_labor_entries')
    op.drop_index(op.f('ix_job_labor_entries_job_id'), table_name='job_labor_entries')
    op.drop_table('job_labor_entries')
    # ### end Alembic commands ###
