"""make labor entry hourly_rate nullable

Revision ID: ccd329b22956
Revises: 8e8d8a5f51bc
Create Date: 2026-08-03 12:12:05.882337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd329b22956'
down_revision = '8e8d8a5f51bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # batch_alter_table, not alter_column: SQLite has no ALTER COLUMN, so it
    # recreates the table instead. MySQL still gets a plain ALTER.
    with op.batch_alter_table('job_labor_entries') as batch_op:
        batch_op.alter_column('hourly_rate', existing_type=sa.Float(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_labor_entries') as batch_op:
        batch_op.alter_column('hourly_rate', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###
